export default () => ({
  port: parseInt(process.env.PORT, 10) || 9090,
  database_url: process.env.DATABASE_URL,
  cloudinary_name: process.env.CLOUDINARY_NAME,
  cloudinary_public: process.env.CLOUDINARY_PUBLIC,
  cloudinary_private: process.env.CLOUDINARY_PRIVATE,
  woo_commerce_public_key: process.env.WOO_COMMERCE_PUBLIC_KEY,
  woo_commerce_private_key: process.env.WOO_COMMERCE_PRIVATE_KEY,
  localhost_src_replacement: process.env.LOCALHOST_SRC_REPLACEMENT,
  jwt_secret: process.env.JWT_SECRET,
  stripe_public_key: process.env.STRIPE_PUBLIC_KEY,
  stripe_private_key: process.env.STRIPE_PRIVATE_KEY,
  recommendationServiceUrl: process.env.RECOMMENDATION_SERVICE_URL,
  mobileAppDirectory: process.env.MOBILE_APP_DIRECTORY,
});
